apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: captcha-api-autoscale
  namespace: captcha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: captcha-api-backend
  minReplicas: 2
  maxReplicas: 15
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    # scaleUp 정책은 필요시 조정하세요(버스트 완화)
    # scaleUp:
    #   stabilizationWindowSeconds: 0
    #   policies:
    #     - type: Percent
    #       value: 100
    #       periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
