apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: captcha-api-autoscale
  namespace: captcha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: captcha-api-backend
  minReplicas: 2
  maxReplicas: 15
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # [수정] CPU 사용률 목표를 30% -> 70%로 상향 조정합니다. 포드가 충분히 일을 하고 있을 때 확장하도록 합니다.