apiVersion: apps/v1
kind: Deployment
metadata:
    name: captcha-api-backend
    namespace: captcha
spec:
    replicas: 2
    selector:
        matchLabels:
            app: captcha-api-backend
    template:
        metadata:
            labels:
                app: captcha-api-backend
        spec:
            nodeSelector:
                node-type: captcha-api
            imagePullSecrets:
                - name: kcr-pull-secret
            containers:
                - name: captcha-api-backend
                  image: kc-sfacspace.kr-central-2.kcr.dev/team1-repo/captcha-api-backend:4531b0ac1852b4d63e819315c11b4087dbb75914
                  ports:
                      - containerPort: 80
