apiVersion: apps/v1
kind: Deployment
metadata:
  name: captcha-api-backend
  namespace: captcha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: captcha-api-backend
  template:
    metadata:
      labels:
        app: captcha-api-backend
    spec:
      nodeSelector:
        node-type: captcha-api
      imagePullSecrets:
      - name: kcr-pull-secret
      containers:
      - name: captcha-api-backend
        image: kc-sfacspace.kr-central-2.kcr.dev/team1-repo/captcha-api-backend:0804dc4cb57591bb8f0b397cf10422bfcc5bbd19
        env:
        - name: ML_SERVICE_URL
          value: "http://ml-service.kubeflow-user-example-com.svc.cluster.local:8001/predict-bot"
        ports:
        - containerPort: 80
