apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: captcha
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      nodeSelector:
        pool-name: platform-pool
      containers:
        - name: website
          image: kc-sfacspace.kr-central-2.kcr.dev/team1-repo/website:0466fc3a3c55ae9ddac909ab90681944524caf5c
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://captcha-api-backend-service.captcha.svc.cluster.local"
            - name: REACT_APP_DEMO_SITE_KEY
              value: "rc_live_f49a055d62283fd02e8203ccaba70fc2"
            # - name: REACT_APP_CAPTCHA_SITE_KEY
            #   value: ""  # 전역 기본키 사용 금지: 사용자별 siteKey를 클라이언트에서 명시적으로 전달하도록 강제
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: kcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: captcha
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  namespace: captcha
  annotations:
    cert-manager.io/cluster-issuer: "kubeflow-self-signing-issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: realcatcha.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-www-ingress
  namespace: captcha
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "https://realcatcha.com"
    cert-manager.io/cluster-issuer: "kubeflow-self-signing-issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: www.realcatcha.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: website-service
              port:
                number: 80