apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Find-Your-Humanity/deploy-manifests
    targetRevision: HEAD
    path: gateway-api
  destination:
    server: https://kubernetes.default.svc
    namespace: captcha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
 