apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: captcha
  labels:
    app: gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      nodeSelector:
        pool-name: platform-pool
      containers:
        - name: gateway-api
          image: kc-sfacspace.kr-central-2.kcr.dev/team1-repo/gateway-api:7b8a64b4b6489cb7078f427e0f48ae89f5feae01
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "az-a.team1-db.1bb3c9ceb1db43928600b93b2a2b1d50.mysql.managed-service.kr-central-2.kakaocloud.com"
            - name: DB_PORT
              value: "13306"
            - name: DB_USER
              value: "realcatcha"
            - name: DB_PASSWORD
              value: "realcatcha"
            - name: DB_NAME
              value: "realcatcha"
            - name: JWT_SECRET_KEY
              value: "realcatcha-jwt-secret-key-2024"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: kcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-backend-service
  namespace: captcha
  labels:
    app: gateway-api
spec:
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
