apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: captcha
  labels:
    app: gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      nodeSelector:
        pool-name: platform-pool
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      containers:
        - name: gateway-api
          image: kc-sfacspace.kr-central-2.kcr.dev/team1-repo/gateway-api:b09c1c5757fc1d541db831b9380f3a3e3f598960
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
          env:
            - name: DB_HOST
              value: "az-a.team1-db.1bb3c9ceb1db43928600b93b2a2b1d50.mysql.managed-service.kr-central-2.kakaocloud.com"
            - name: DB_PORT
              value: "13306"
            - name: DB_USER
              value: "realcatcha"
            - name: DB_PASSWORD
              value: "realcatcha"
            - name: DB_NAME
              value: "captcha"
            - name: JWT_SECRET_KEY
              value: "realcatcha-jwt-secret-key-2024"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secrets
                  key: client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secrets
                  key: client-secret
            - name: GOOGLE_REDIRECT_URI
              value: "https://realcatcha.com/auth/google/callback"
            - name: TZ
              value: "Asia/Seoul"
          resources:
            requests:
              memory: "16Gi"
              cpu: "5"
            limits:
              memory: "32Gi"
              cpu: "8"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: kcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-backend-service
  namespace: captcha
  labels:
    app: gateway-api
spec:
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
